### ISSUE TITLE
page-process.php

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#11]
This page template should use more custom fields. 🤔

It shouldn't be too tough to add some fields for these pages.
I also noticed these pages don't have template names, I guess it's just using the template hierarchy? 

If you are having trouble adding fields to just this page try adding a template name e.g.
```
/**
 * Template Name: Process

**Comment by temefleet** [comment]
Changed some content to custom fields and added the template name.

**Comment by rcass** [comment]
There is still quite a bit of content in the template. Basically if it something that the client would want to enter or change in the future it should be accessible though the WordPress admin area (aka prob make it a custom field)

For example, that bean content could be stored using a CFS loop. You may not have time for it tomorrow, but should be something changed if the client goes forward.

**Comment by temefleet** [comment]
The reason we chose not to make the a custom field is because of the bean logo. We figured they would need to have the bean icon as well which was created by the designers. I guess any logo could be placed in there, but that was our reasoning anyways.

**Comment by rcass** [comment]
I guess my arguement would be the text could be something the client would want to access, just in case the want to change the wording, etc.

Also, if you have the bean logo just a upload field, it means that if the designer made another bean, then could add it right away. With the current was it is built, the client would have to hire both a designer and developer to make those changes.

Also, adding the content on the page makes the theme a less reuseable. Since the content will always be displayed on the page and then requires a dev to change that.

**Comment by temefleet** [comment]
Good points. We changed it to custom fields. Thanks!
