### ISSUE TITLE
archive-workshop.php html for style

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/evr-summer-2017#3]
line 25 <div class="h2-line"></div>
You could replace this html with css 
e.g. 
.workshops-content h2 { border-bottom: 1px solid white; }
would look the same

Generally if we can achieve the same style without adding extra html that's the preferred way.

**Comment by ghost** [comment]
done.

**Comment by rcass** [comment]
Going back to Jim's recommendation, try adding that style without adding a class, since it doesn't really seem you need to because you can use a descendant selector (aka jim's example above). Basically avoiding adding unnecessary markup and working with what already exists on the page.

So just please try removing that div and just using css 👍 

- [x] Remove `<div class="h2-line"></div>` and use just CSS instead

**Comment by temefleet** [comment]
Removed the unnecessary html div and put the styles on the h2. All other instances of that line are styled on the h2.

**Comment by rcass** [comment]
Awesome! 🎉
